In [45]:
import tensorflow as tf
from tensorflow import keras
tf.__version__
keras.__version__

'2.9.0'

In [46]:
df = keras.datasets.fashion_mnist
(X_train, y_train), (X_test, y_test) = df.load_data()

In [47]:
X_train = X_train.reshape(60000, 784) / 255.0
X_test = X_test.reshape(10000, 784) / 255.0

## Model1

In [48]:
model1 = keras.models.Sequential()
model1.add(keras.layers.Flatten()) 
model1.add(keras.layers.Flatten(input_shape=[28, 28])) 
model1.add(keras.layers.Dense(4, activation='relu'))
model1.add(tf.keras.layers.Dense(10, activation='softmax'))

In [49]:
model1.compile(loss="sparse_categorical_crossentropy", metrics=["accuracy"], optimizer="sgd")
history = model1.fit(X_train, y_train, epochs=10, validation_split=0.30)

Epoch 1/10
1313/1313 [==============================] - 4s 3ms/step - loss: 1.5658 - accuracy: 0.4775 - val_loss: 1.1089 - val_accuracy: 0.6370
Epoch 2/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.9037 - accuracy: 0.6862 - val_loss: 0.7887 - val_accuracy: 0.7128
Epoch 3/10
1313/1313 [==============================] - 3s 2ms/step - loss: 0.7414 - accuracy: 0.7393 - val_loss: 0.7108 - val_accuracy: 0.7501
Epoch 4/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.6810 - accuracy: 0.7676 - val_loss: 0.6640 - val_accuracy: 0.7729
Epoch 5/10
1313/1313 [==============================] - 4s 3ms/step - loss: 0.6435 - accuracy: 0.7813 - val_loss: 0.6790 - val_accuracy: 0.7477
Epoch 6/10
1313/1313 [==============================] - 3s 2ms/step - loss: 0.6175 - accuracy: 0.7922 - val_loss: 0.6062 - val_accuracy: 0.7954
Epoch 7/10
1313/1313 [==============================] - 3s 2ms/step - loss: 0.5985 - accuracy: 0.7959 - val_loss: 0.5937 - val_accuracy:

## Model1 evaluation

In [50]:
model1.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.5957 - accuracy: 0.7966


[0.5957294702529907, 0.7965999841690063]

In [51]:
X_new = X_test[:3]
y_proba = model1.predict(X_new) 
y_proba.round(2)

1/1 [==============================] - 0s 57ms/step


array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.33, 0.  , 0.19, 0.  , 0.47],
       [0.  , 0.  , 0.66, 0.  , 0.19, 0.  , 0.15, 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]],
      dtype=float32)

In [52]:
AccuracyModel1 = model1.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.5957 - accuracy: 0.7966


## Model2 

In [53]:
model2 = keras.models.Sequential()
model2.add(keras.layers.Flatten()) 
model2.add(keras.layers.Flatten(input_shape=[28, 28])) 
model2.add(keras.layers.Dense(4, activation='sigmoid'))
model2.add(tf.keras.layers.Dense(10, activation='softmax'))

In [54]:
model2.compile(loss="sparse_categorical_crossentropy", metrics=["accuracy"], optimizer="sgd")
history = model2.fit(X_train, y_train, epochs=10, validation_split=0.30)

Epoch 1/10
1313/1313 [==============================] - 4s 3ms/step - loss: 2.1218 - accuracy: 0.3415 - val_loss: 1.9255 - val_accuracy: 0.5169
Epoch 2/10
1313/1313 [==============================] - 3s 3ms/step - loss: 1.7516 - accuracy: 0.5556 - val_loss: 1.5946 - val_accuracy: 0.6030
Epoch 3/10
1313/1313 [==============================] - 4s 3ms/step - loss: 1.4823 - accuracy: 0.6108 - val_loss: 1.3798 - val_accuracy: 0.6336
Epoch 4/10
1313/1313 [==============================] - 4s 3ms/step - loss: 1.3096 - accuracy: 0.6318 - val_loss: 1.2411 - val_accuracy: 0.6503
Epoch 5/10
1313/1313 [==============================] - 3s 2ms/step - loss: 1.1950 - accuracy: 0.6462 - val_loss: 1.1463 - val_accuracy: 0.6588
Epoch 6/10
1313/1313 [==============================] - 3s 2ms/step - loss: 1.1133 - accuracy: 0.6570 - val_loss: 1.0760 - val_accuracy: 0.6679
Epoch 7/10
1313/1313 [==============================] - 3s 2ms/step - loss: 1.0501 - accuracy: 0.6658 - val_loss: 1.0205 - val_accuracy:

## Model2 Evaluation

In [55]:
model2.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.9158 - accuracy: 0.7059


[0.9157586097717285, 0.7059000134468079]

In [56]:
X_new = X_test[:3]
y_proba = model2.predict(X_new) 
y_proba.round(2)

1/1 [==============================] - 0s 66ms/step


array([[0.  , 0.02, 0.01, 0.  , 0.01, 0.19, 0.01, 0.08, 0.05, 0.63],
       [0.03, 0.01, 0.31, 0.04, 0.26, 0.02, 0.26, 0.  , 0.06, 0.01],
       [0.01, 0.83, 0.01, 0.09, 0.02, 0.  , 0.01, 0.01, 0.  , 0.03]],
      dtype=float32)

In [57]:
AccuracyModel2 = model2.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.9158 - accuracy: 0.7059


## Model3 

In [58]:
model3 = keras.models.Sequential() 
model3.add(keras.layers.Flatten()) 
model3.add(keras.layers.Flatten(input_shape=[28, 28])) 
model3.add(keras.layers.Dense(100, activation="relu")) 
model3.add(keras.layers.Dense(300, activation="relu")) 
model3.add(keras.layers.BatchNormalization()) 
model3.add(keras.layers.Dropout(rate=0.25)) 
model3.add(keras.layers.Dense(10, activation="softmax"))

In [59]:
model3.compile(loss="sparse_categorical_crossentropy", metrics=["accuracy"], optimizer="sgd")
history = model3.fit(X_train, y_train, epochs=30, validation_split=0.30)

Epoch 1/30
1313/1313 [==============================] - 8s 5ms/step - loss: 0.6057 - accuracy: 0.7875 - val_loss: 0.5324 - val_accuracy: 0.8076
Epoch 2/30
1313/1313 [==============================] - 6s 4ms/step - loss: 0.4563 - accuracy: 0.8382 - val_loss: 0.4145 - val_accuracy: 0.8522
Epoch 3/30
1313/1313 [==============================] - 6s 4ms/step - loss: 0.4146 - accuracy: 0.8526 - val_loss: 0.4252 - val_accuracy: 0.8508
Epoch 4/30
1313/1313 [==============================] - 6s 5ms/step - loss: 0.3841 - accuracy: 0.8607 - val_loss: 0.4045 - val_accuracy: 0.8538
Epoch 5/30
1313/1313 [==============================] - 6s 4ms/step - loss: 0.3671 - accuracy: 0.8675 - val_loss: 0.3715 - val_accuracy: 0.8673
Epoch 6/30
1313/1313 [==============================] - 6s 4ms/step - loss: 0.3519 - accuracy: 0.8722 - val_loss: 0.3513 - val_accuracy: 0.8724
Epoch 7/30
1313/1313 [==============================] - 6s 5ms/step - loss: 0.3391 - accuracy: 0.8767 - val_loss: 0.3559 - val_accuracy:

## Model3 Evaluation 

In [60]:
model3.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.3559 - accuracy: 0.8817


[0.3559342920780182, 0.8816999793052673]

In [61]:
X_new = X_test[:3]
y_proba = model3.predict(X_new) 
y_proba.round(2)

1/1 [==============================] - 0s 71ms/step


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [62]:
AccuracyModel3 = model3.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.3559 - accuracy: 0.8817


## Combined model

In [63]:
CombinedModel = [model1, model2, model3]

In [64]:
for model in CombinedModel:
  model.fit(X_test, y_train, epochs=30, validation_split=0.3)
  data = model.evaluate(X_test, y_test)
  print('Combined Model Loss is: {} and Combined Model Accuracy is: {}'.format(data[0],data[1]))

Epoch 1/30
219/219 [==============================] - 1s 3ms/step - loss: 3.6160 - accuracy: 0.1007 - val_loss: 2.7388 - val_accuracy: 0.0940
Epoch 2/30
219/219 [==============================] - 1s 3ms/step - loss: 2.6146 - accuracy: 0.0993 - val_loss: 2.5313 - val_accuracy: 0.0947
Epoch 3/30
219/219 [==============================] - 1s 2ms/step - loss: 2.4720 - accuracy: 0.0993 - val_loss: 2.4351 - val_accuracy: 0.0950
Epoch 4/30
219/219 [==============================] - 1s 3ms/step - loss: 2.4025 - accuracy: 0.1001 - val_loss: 2.3842 - val_accuracy: 0.0970
Epoch 5/30
219/219 [==============================] - 1s 3ms/step - loss: 2.3641 - accuracy: 0.1003 - val_loss: 2.3547 - val_accuracy: 0.0970
Epoch 6/30
219/219 [==============================] - 1s 3ms/step - loss: 2.3413 - accuracy: 0.1003 - val_loss: 2.3369 - val_accuracy: 0.0957
Epoch 7/30
219/219 [==============================] - 1s 3ms/step - loss: 2.3273 - accuracy: 0.1006 - val_loss: 2.3259 - val_accuracy: 0.0953
Epoch 

In [65]:
AvgAllModels = (AccuracyModel1[1] + AccuracyModel2[1] + AccuracyModel3[1])/3

## Avg of all the 3 models

In [66]:
AvgAllModels

0.7947333256403605